SIMPLE_GEO_TOKEN = "ENTER YOUR OAUTH TOKEN HERE"
SIMPLE_GEO_SECRET = "ENTER YOUR OAUTH SECRET HERE"
SIMPLE_GEO_LAYER = "ENTER YOUR SIMPLE GEO DATA LAYER HERE"

SLEEP_TIME = 30.0

TWITTER_SEARCH_URL = "http://search.twitter.com/search.json?%s"